"""The ownership migrations, exercised the way a migration actually runs.

A migration is the one path that does not go through the ORM, so it is the one
path both other test layers are blind to (they create rows through SQLAlchemy,
and the e2e database is reseeded from scratch). This mirrors
`test_loudness_migration.py`, which exists because an autogenerated draft once
proposed a statement SQLite cannot execute at all — and the same spurious
`playlists.kind` re-type keeps reappearing in every new draft since.

Renamed from `test_owner_key_migration.py` when #170 moved ownership from the
access key to an install. The P12 assertions are gone with the column, but the
reason for the file is unchanged: the Docker image runs `alembic upgrade head` on
boot, so a statement SQLite rejects stops the app starting rather than merely
failing a test.
"""

import logging
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import IntegrityError

BACKEND_ROOT = Path(__file__).resolve().parents[1]

OWNED_TABLES = ("songs", "playlists", "import_jobs", "playlist_imports")


@pytest.fixture
def migrated_db(tmp_path):
    """A database built by running the real migrations, start to finish."""
    db_path = tmp_path / "migration.db"
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    url = f"sqlite:///{db_path}"
    config.attributes["sqlalchemy.url"] = url
    return config, url


def test_upgrade_runs_and_adds_owner_install_id_everywhere(migrated_db):
    """The whole chain must execute on SQLite — the Docker image runs
    `alembic upgrade head` on boot, so a statement SQLite rejects stops the app
    starting, not just this test."""
    config, url = migrated_db
    command.upgrade(config, "head")

    inspector = inspect(create_engine(url))
    assert "installs" in inspector.get_table_names()
    for table in OWNED_TABLES:
        columns = {c["name"] for c in inspector.get_columns(table)}
        assert "owner_install_id" in columns, table
        # The old column is gone, not left alongside: two owner columns, one of
        # them dead, is what gets read by accident a year later.
        assert "owner_key_id" not in columns, table


def test_rows_written_before_the_migration_survive_it(migrated_db):
    """Existing rows are the local, unowned library and must remain readable.

    Written as raw SQL at the *previous* revision, because that is what a real
    upgrade meets: rows the ORM never touched. Enum columns are included on
    purpose — `native_enum=False` persists the enum NAME, and a migration that
    writes the lowercase value instead makes pre-existing rows unreadable at
    runtime (the Wave-F landmine).
    """
    config, url = migrated_db
    command.upgrade(config, "56a066fc4e19")

    engine = create_engine(url)
    with engine.begin() as conn:
        conn.execute(
            text(
                "INSERT INTO songs (title, artist, file_path, file_hash, source_url,"
                " source_platform, added_at)"
                " VALUES ('Old', 'Artist', '/x.opus', 'h', 'u', 'youtube', '2026-01-01')"
            )
        )
        conn.execute(
            text(
                "INSERT INTO playlists (name, kind, created_at, updated_at)"
                " VALUES ('Mine', 'USER', '2026-01-01', '2026-01-01')"
            )
        )

    command.upgrade(config, "head")

    with engine.begin() as conn:
        song = conn.execute(text("SELECT title, owner_install_id FROM songs")).one()
        playlist = conn.execute(text("SELECT name, kind, owner_install_id FROM playlists")).one()

    assert song == ("Old", None)
    # The enum still reads as the NAME, not the value.
    assert playlist == ("Mine", "USER", None)


def test_downgrade_restores_the_key_column_and_drops_installs(migrated_db):
    """A downgrade has to be executable, not merely written. Dropping a column on
    SQLite needs batch mode, which rebuilds the table — the one step in this
    revision most likely to fail only when actually run."""
    config, url = migrated_db
    command.upgrade(config, "head")
    command.downgrade(config, "1220936506e0")

    inspector = inspect(create_engine(url))
    assert "installs" not in inspector.get_table_names()
    for table in OWNED_TABLES:
        columns = {c["name"] for c in inspector.get_columns(table)}
        assert "owner_install_id" not in columns, table
        assert "owner_key_id" in columns, table


def test_an_install_token_hash_must_be_unique(migrated_db):
    """One token, one install. Without the unique index a duplicated token would
    silently create a second library nobody could reach."""
    config, url = migrated_db
    command.upgrade(config, "head")

    engine = create_engine(url)
    with engine.begin() as conn:
        conn.execute(
            text("INSERT INTO installs (token_hash, created_at) VALUES ('abc', '2026-01-01')")
        )
    # Specifically an integrity error — a blind `Exception` would also pass if
    # the INSERT failed for an unrelated reason, proving nothing.
    with pytest.raises(IntegrityError):
        with engine.begin() as conn:
            conn.execute(
                text("INSERT INTO installs (token_hash, created_at) VALUES ('abc', '2026-01-02')")
            )


def test_running_migrations_does_not_reconfigure_global_logging(migrated_db, caplog):
    """Alembic's `env.py` calls `fileConfig`, which replaces root handlers and
    disables existing loggers *globally*.

    Left unguarded that breaks `caplog` for every test that runs afterwards, with
    nothing to connect cause to effect — renaming this file moved it alphabetically
    ahead of `test_logging.py` and made two unrelated tests fail. `env.py` now
    skips `fileConfig` when a caller supplies the URL, i.e. when driven from here.
    """
    config, _ = migrated_db
    command.upgrade(config, "head")

    with caplog.at_level(logging.INFO, logger="test.after.migration"):
        logging.getLogger("test.after.migration").info("still captured")

    # Filtered by logger: caplog also holds alembic's own migration chatter, and
    # asserting on the whole list would be asserting about alembic.
    mine = [r.message for r in caplog.records if r.name == "test.after.migration"]
    assert mine == ["still captured"]
