"""The G4 migration, exercised the way a migration actually runs.

Both of this track's recorded landmines live here: a migration is the one path
that does *not* go through the ORM, and the enum column it sits next to has
already been broken once by a well-meaning autogenerated `alter_column`.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text

BACKEND_ROOT = Path(__file__).resolve().parents[1]
REVISION = "56a066fc4e19"


@pytest.fixture
def migrated_db(tmp_path):
    """A database built by running the real migrations, start to finish."""
    db_path = tmp_path / "migration.db"
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    # Handed through config.attributes, which is alembic's channel for a
    # programmatic caller — env.py otherwise takes the app's own DATABASE_URL,
    # which conftest has already pointed at a shared, ORM-created database.
    url = f"sqlite:///{db_path}"
    config.attributes["sqlalchemy.url"] = url
    return config, url


def test_upgrade_adds_the_loudness_columns(migrated_db):
    config, url = migrated_db
    command.upgrade(config, "head")

    columns = {c["name"] for c in inspect(create_engine(url)).get_columns("songs")}

    assert "loudness_lufs" in columns
    assert "peak_dbfs" in columns


def test_existing_songs_survive_with_no_measurement(migrated_db):
    """A row that predates the columns must read back as "not analysed"."""
    config, url = migrated_db
    command.upgrade(config, "b7d2e5a91c33")

    engine = create_engine(url)
    with engine.begin() as conn:
        conn.execute(
            text(
                "INSERT INTO songs (title, artist, file_path, file_hash, source_url,"
                " source_platform, added_at) VALUES ('Old', 'Artist', '/x.opus',"
                " 'hash', 'https://example.com/1', 'Youtube', '2026-01-01T00:00:00')"
            )
        )

    command.upgrade(config, "head")

    with engine.connect() as conn:
        row = conn.execute(text("SELECT loudness_lufs, peak_dbfs FROM songs")).one()
    assert row == (None, None)


def test_does_not_disturb_the_playlist_kind_enum(migrated_db):
    """Autogenerate wanted to re-type `playlists.kind`; it must not.

    That column stores the enum's NAME, and rewriting it is what made every
    pre-existing playlist unreadable once already. SQLite applies a type change
    by rebuilding the whole table, so a stray `alter_column` here is a real
    risk, not a cosmetic one. This writes the raw value a migration would and
    checks it still reads back untouched.
    """
    config, url = migrated_db
    command.upgrade(config, "b7d2e5a91c33")

    engine = create_engine(url)
    with engine.begin() as conn:
        conn.execute(
            text(
                "INSERT INTO playlists (name, kind, created_at, updated_at)"
                " VALUES ('Older', 'USER', '2026-01-01T00:00:00', '2026-01-01T00:00:00')"
            )
        )

    command.upgrade(config, "head")

    with engine.connect() as conn:
        kind = conn.execute(text("SELECT kind FROM playlists")).scalar_one()
    assert kind == "USER"


def test_downgrade_removes_only_the_new_columns(migrated_db):
    config, url = migrated_db
    # Upgrade to *this* revision rather than head, then step back one. Using
    # head assumed the loudness migration was the newest one, which stopped
    # being true the moment another revision landed on top of it (P12).
    command.upgrade(config, REVISION)
    command.downgrade(config, "-1")

    engine = create_engine(url)
    columns = {c["name"] for c in inspect(engine).get_columns("songs")}
    assert "loudness_lufs" not in columns
    assert "peak_dbfs" not in columns
    # The rest of the table is still there.
    assert {"title", "artist", "file_path"} <= columns
    # And the playlists table came through the round trip intact.
    assert "kind" in {c["name"] for c in inspect(engine).get_columns("playlists")}
