import { DatabaseSync } from 'node:sqlite'

import { MIGRATIONS } from '../src/library/db'

/**
 * The v2 migration, run for real (#246).
 *
 * `libraryDb.test.ts` drives a fake that records which migrations ran. That is
 * the right test for the *runner* and says nothing about whether the SQL works —
 * and v2 rebuilds the `songs` table, which is the kind of migration this project
 * has already been bitten by (`docs/lessons.md`: an autogenerated migration is a
 * draft, not a diff).
 *
 * So this executes the real statements against a real SQLite. Node 22 ships
 * `node:sqlite`, and the app's engine is the same SQLite, so the dialect being
 * exercised is the one that will run on the phone.
 *
 * The failure this exists to catch is a device that cannot open its own library,
 * or opens it with everything silently gone — neither of which a mock can find.
 */

function migratedTo(version: number): DatabaseSync {
  const db = new DatabaseSync(':memory:')
  for (let index = 0; index < version; index++) {
    db.exec(MIGRATIONS[index])
  }
  return db
}

/** A v1 row, written the way v1's schema expects — keyed by the server's id. */
function insertV1Song(db: DatabaseSync, id: number, fileUri: string | null) {
  db.prepare(
    `INSERT INTO songs
       (id, title, artist, album, duration, source_url, source_platform,
        added_at, loudness_lufs, peak_dbfs, file_uri, file_size)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  ).run(
    id,
    `Song ${id}`,
    'Artist',
    null,
    200,
    `https://youtube.com/watch?v=${id}`,
    'Youtube',
    '2026-07-30T00:00:00Z',
    -12,
    -1,
    fileUri,
    fileUri ? 4096 : null,
  )
}

describe('the v2 migration — the library mints its own ids (#246)', () => {
  it('runs at all, on a database that already has v1', () => {
    const db = migratedTo(1)
    expect(() => db.exec(MIGRATIONS[1])).not.toThrow()
  })

  it('keeps every existing song, with the server id moved to its own column', () => {
    const db = migratedTo(1)
    insertV1Song(db, 42, 'file:///data/app/library/42.opus')
    insertV1Song(db, 43, null)

    db.exec(MIGRATIONS[1])

    const rows = db.prepare('SELECT * FROM songs ORDER BY server_song_id').all() as Record<
      string,
      unknown
    >[]
    expect(rows).toHaveLength(2)
    expect(rows.map((r) => r.server_song_id)).toEqual([42, 43])
    expect(rows[0].title).toBe('Song 42')
    // The audio is not re-downloaded by a migration, so the recorded location
    // has to survive it — and it still names the *old* id, which is why
    // deletion prefers `file_uri` over recomputing the path.
    expect(rows[0].file_uri).toBe('file:///data/app/library/42.opus')
    expect(rows[0].file_size).toBe(4096)
    expect(rows[1].file_uri).toBeNull()
  })

  it('gives every migrated row a local id of the same shape the app mints', () => {
    const db = migratedTo(1)
    insertV1Song(db, 42, null)
    insertV1Song(db, 43, null)

    db.exec(MIGRATIONS[1])

    const ids = (db.prepare('SELECT id FROM songs').all() as { id: string }[]).map((r) => r.id)
    // 16 bytes hex — `randomHex(16)` in the app, `hex(randomblob(16))` here.
    for (const id of ids) expect(id).toMatch(/^[0-9a-f]{32}$/)
    expect(new Set(ids).size).toBe(2)
  })

  it('refuses two local rows claiming the same server song', () => {
    // This constraint is what makes the import handover idempotent (#215): the
    // upsert in `saveSongMetadata` keys on it. Without it, re-importing a track
    // would quietly create a second copy under a fresh local id.
    const db = migratedTo(2)
    const insert = db.prepare(
      `INSERT INTO songs (id, server_song_id, title, artist, source_url, source_platform, added_at)
       VALUES (?, ?, 'T', 'A', 'u', 'Youtube', '2026-07-30T00:00:00Z')`,
    )
    insert.run('aaaa', 7)

    expect(() => insert.run('bbbb', 7)).toThrow(/UNIQUE/i)
  })

  it('allows many songs with no server id at all', () => {
    // The point of the whole change: a song this device fetched itself has no
    // server row. SQLite treats NULLs as distinct for UNIQUE, and this pins
    // that — if it did not hold, the second device-side import would fail.
    const db = migratedTo(2)
    const insert = db.prepare(
      `INSERT INTO songs (id, server_song_id, title, artist, source_url, source_platform, added_at)
       VALUES (?, NULL, 'T', 'A', 'u', 'Youtube', '2026-07-30T00:00:00Z')`,
    )
    insert.run('aaaa')
    insert.run('bbbb')

    expect(db.prepare('SELECT COUNT(*) AS n FROM songs').get()).toMatchObject({ n: 2 })
  })

  it('leaves the indexes in place afterwards', () => {
    // The table is dropped and recreated, so indexes created in v1 go with it.
    const db = migratedTo(2)
    const names = (
      db.prepare("SELECT name FROM sqlite_master WHERE type = 'index'").all() as { name: string }[]
    ).map((r) => r.name)

    expect(names).toEqual(expect.arrayContaining(['songs_added_at', 'songs_title']))
    expect(names).toContain('songs_server_id')
  })
})

describe('the v3 migration — playlists and favourites move local (#219)', () => {
  it('creates favourites itself, so no code path has to wonder', () => {
    const db = migratedTo(3)

    const rows = db.prepare("SELECT name, kind FROM playlists WHERE kind = 'favourites'").all()
    // Seeded by the migration for the same reason the backend seeds it: every
    // caller can assume it exists rather than each deciding to create it.
    expect(rows).toHaveLength(1)
    expect(rows[0]).toMatchObject({ name: 'Favourites', kind: 'favourites' })
  })

  it('does not create a second favourites on a database that has one', () => {
    // Migrations run once per device, but "once" is a claim about bookkeeping;
    // the statement is written so that running it twice is still correct.
    const db = migratedTo(3)
    db.exec(MIGRATIONS[2])

    expect(
      db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind='favourites'").get(),
    ).toMatchObject({ n: 1 })
  })

  it('refuses two songs at the same position in one playlist', () => {
    // Dense, 0-based positions were the server's invariant; here the index
    // enforces it, so a bug cannot quietly leave a duplicate.
    const db = migratedTo(3)
    const insert = db.prepare(
      'INSERT INTO playlist_items (id, playlist_id, song_id, position) VALUES (?, ?, ?, ?)',
    )
    insert.run('i1', 'p1', 's1', 0)

    expect(() => insert.run('i2', 'p1', 's2', 0)).toThrow(/UNIQUE/i)
  })

  it('refuses the same song twice in one playlist', () => {
    const db = migratedTo(3)
    const insert = db.prepare(
      'INSERT INTO playlist_items (id, playlist_id, song_id, position) VALUES (?, ?, ?, ?)',
    )
    insert.run('i1', 'p1', 's1', 0)

    // What a heart button means, and simpler to reason about than the server's
    // rule of "duplicates allowed except in favourites".
    expect(() => insert.run('i2', 'p1', 's1', 1)).toThrow(/UNIQUE/i)
  })

  it('allows the same position and the same song in different playlists', () => {
    const db = migratedTo(3)
    const insert = db.prepare(
      'INSERT INTO playlist_items (id, playlist_id, song_id, position) VALUES (?, ?, ?, ?)',
    )
    insert.run('i1', 'p1', 's1', 0)

    expect(() => insert.run('i2', 'p2', 's1', 0)).not.toThrow()
  })

  it('leaves the songs table alone', () => {
    // v3 is additive. A migration that rebuilt `songs` again would be a way to
    // lose a library, and there is no reason for it to touch that table.
    const db = migratedTo(2)
    insertV1Song(db, 42, 'file:///library/42.opus')
    db.exec(MIGRATIONS[2])

    expect(db.prepare('SELECT COUNT(*) AS n FROM songs').get()).toMatchObject({ n: 1 })
  })
})

describe('the v4 migration — a playlist remembers its server import (#225)', () => {
  it('adds the column without rebuilding the table', () => {
    const db = migratedTo(3)
    db.prepare(
      `INSERT INTO playlists (id, name, kind, created_at, updated_at)
       VALUES ('p1', 'Road Trip', 'user', '', '')`,
    ).run()

    db.exec(MIGRATIONS[3])

    // `ALTER TABLE ... ADD COLUMN` needs no rebuild, so nothing here can lose
    // a library — and the favourites row seeded by v3 has to survive.
    expect(db.prepare('SELECT COUNT(*) AS n FROM playlists').get()).toMatchObject({ n: 2 })
    expect(
      db.prepare("SELECT server_playlist_id FROM playlists WHERE id = 'p1'").get(),
    ).toMatchObject({ server_playlist_id: null })
  })

  it('refuses two local playlists claiming the same server import', () => {
    // What stops reopening a finished import building a second playlist every
    // time — the job `songs.server_song_id` does for songs.
    const db = migratedTo(4)
    const insert = db.prepare(
      `INSERT INTO playlists (id, name, kind, created_at, updated_at, server_playlist_id)
       VALUES (?, 'X', 'user', '', '', 9)`,
    )
    insert.run('a')

    expect(() => insert.run('b')).toThrow(/UNIQUE/i)
  })

  it('allows many playlists with no server import', () => {
    const db = migratedTo(4)
    const insert = db.prepare(
      `INSERT INTO playlists (id, name, kind, created_at, updated_at, server_playlist_id)
       VALUES (?, 'X', 'user', '', '', NULL)`,
    )
    insert.run('a')

    // SQLite treats NULLs as distinct for UNIQUE; without that, a second
    // device-made playlist would fail.
    expect(() => insert.run('b')).not.toThrow()
  })
})

describe('the v5 migration — covers on the device (#218)', () => {
  it('adds the column without touching the songs already there', () => {
    const db = migratedTo(4)
    db.prepare(
      `INSERT INTO songs
         (id, server_song_id, title, artist, album, duration, source_url,
          source_platform, added_at, loudness_lufs, peak_dbfs, file_uri, file_size)
       VALUES ('s1', 7, 'Kept', 'Artist', NULL, 200, 'https://y/1', 'Youtube',
               '2026-07-30T00:00:00Z', -12, -1, 'file:///library/s1.opus', 4096)`,
    ).run()

    db.exec(MIGRATIONS[4])

    // `ALTER TABLE ... ADD COLUMN` needs no rebuild, which is the whole reason
    // this migration cannot lose a library the way a table rebuild could.
    const row = db.prepare("SELECT * FROM songs WHERE id = 's1'").get()
    expect(row).toMatchObject({
      title: 'Kept',
      file_uri: 'file:///library/s1.opus',
      // Existing songs have no cover yet. Null is an ordinary state, and
      // re-running an import is what fills it in later.
      cover_uri: null,
    })
  })

  it('accepts a cover path once one is recorded', () => {
    const db = migratedTo(5)
    db.prepare(
      `INSERT INTO songs
         (id, server_song_id, title, artist, album, duration, source_url,
          source_platform, added_at, loudness_lufs, peak_dbfs, file_uri,
          file_size, cover_uri)
       VALUES ('s1', NULL, 'X', 'A', NULL, 1, 'https://y/1', 'Youtube', '', NULL,
               NULL, NULL, NULL, 'file:///library/s1.jpg')`,
    ).run()

    expect(db.prepare("SELECT cover_uri FROM songs WHERE id = 's1'").get()).toMatchObject({
      cover_uri: 'file:///library/s1.jpg',
    })
  })

  it('leaves the indexes v2 and v3 created in place', () => {
    const db = migratedTo(5)

    const names = db
      .prepare("SELECT name FROM sqlite_master WHERE type = 'index'")
      .all()
      .map((row) => (row as { name: string }).name)

    expect(names).toEqual(expect.arrayContaining(['songs_added_at', 'songs_server_id']))
  })
})

/**
 * The v6 migration — one row per source, and an import id of its own
 * (#308, #310).
 *
 * The one that could brick a library. `CREATE UNIQUE INDEX` on a column that
 * already holds duplicates throws, the transaction rolls back, and the app
 * cannot open its own database — so the duplicates have to be merged in the
 * same breath, and that merge has to keep the right row.
 */
describe('the v6 migration — one row per source (#308, #310)', () => {
  /** A song row as v5 stores them: a local text id, an optional server id. */
  function insertSong(
    db: DatabaseSync,
    row: {
      id: string
      serverSongId: number | null
      sourceUrl: string
      fileUri: string | null
      addedAt?: string
      title?: string
    },
  ) {
    db.prepare(
      `INSERT INTO songs
         (id, server_song_id, title, artist, album, duration, source_url,
          source_platform, added_at, loudness_lufs, peak_dbfs, file_uri, file_size)
       VALUES (?, ?, ?, ?, NULL, ?, ?, ?, ?, ?, NULL, ?, ?)`,
    ).run(
      row.id,
      row.serverSongId,
      row.title ?? 'Song',
      'Artist',
      200,
      row.sourceUrl,
      'Youtube',
      row.addedAt ?? '2026-08-01T00:00:00Z',
      -12,
      row.fileUri,
      row.fileUri ? 4096 : null,
    )
  }

  function insertPlaylist(db: DatabaseSync, id: string, serverPlaylistId: number | null) {
    db.prepare(
      `INSERT INTO playlists (id, name, kind, created_at, updated_at, server_playlist_id)
       VALUES (?, ?, 'user', ?, ?, ?)`,
    ).run(id, `Playlist ${id}`, '2026-08-01T00:00:00Z', '2026-08-01T00:00:00Z', serverPlaylistId)
  }

  function insertItem(
    db: DatabaseSync,
    id: string,
    playlistId: string,
    songId: string,
    pos: number,
  ) {
    db.prepare(
      'INSERT INTO playlist_items (id, playlist_id, song_id, position) VALUES (?, ?, ?, ?)',
    ).run(id, playlistId, songId, pos)
  }

  const SAME = 'https://www.youtube.com/watch?v=abc'

  it('runs on a v5 database that already holds duplicates', () => {
    const db = migratedTo(5)
    // Exactly the shape #310 describes: the same video arrived once through the
    // server path and once through a device import, so the de-dupe missed it.
    insertSong(db, { id: 'a', serverSongId: 7, sourceUrl: SAME, fileUri: 'file:///a.opus' })
    insertSong(db, { id: 'b', serverSongId: null, sourceUrl: SAME, fileUri: null })

    expect(() => db.exec(MIGRATIONS[5])).not.toThrow()
  })

  it('keeps the copy that has the audio, not merely the older one', () => {
    const db = migratedTo(5)
    // The one with the file is the *newer* row here, so a naive "keep the
    // oldest" would delete the download and leave the library insisting it does
    // not have a track whose bytes are sitting on disk.
    insertSong(db, {
      id: 'older',
      serverSongId: 7,
      sourceUrl: SAME,
      fileUri: null,
      addedAt: '2026-07-01T00:00:00Z',
    })
    insertSong(db, {
      id: 'newer',
      serverSongId: null,
      sourceUrl: SAME,
      fileUri: 'file:///newer.opus',
      addedAt: '2026-08-01T00:00:00Z',
    })

    db.exec(MIGRATIONS[5])

    const rows = db.prepare('SELECT id, file_uri FROM songs').all() as {
      id: string
      file_uri: string | null
    }[]
    expect(rows).toEqual([{ id: 'newer', file_uri: 'file:///newer.opus' }])
  })

  it('keeps the older copy when neither has audio', () => {
    const db = migratedTo(5)
    insertSong(db, {
      id: 'older',
      serverSongId: null,
      sourceUrl: SAME,
      fileUri: null,
      addedAt: '2026-07-01T00:00:00Z',
    })
    insertSong(db, {
      id: 'newer',
      serverSongId: null,
      sourceUrl: SAME,
      fileUri: null,
      addedAt: '2026-08-01T00:00:00Z',
    })

    db.exec(MIGRATIONS[5])

    expect(db.prepare('SELECT id FROM songs').all()).toEqual([{ id: 'older' }])
  })

  it('moves playlist membership onto the row that survives', () => {
    const db = migratedTo(5)
    insertSong(db, {
      id: 'keeper',
      serverSongId: 7,
      sourceUrl: SAME,
      fileUri: 'file:///a.opus',
      addedAt: '2026-07-01T00:00:00Z',
    })
    insertSong(db, { id: 'loser', serverSongId: null, sourceUrl: SAME, fileUri: null })
    insertPlaylist(db, 'p1', null)
    // The playlist points at the row that is about to be deleted, which is the
    // whole hazard: a merge that forgets this empties the playlist.
    insertItem(db, 'i1', 'p1', 'loser', 0)

    db.exec(MIGRATIONS[5])

    const items = db.prepare('SELECT song_id FROM playlist_items').all()
    expect(items).toEqual([{ song_id: 'keeper' }])
  })

  it('repoints onto the copy with the audio even when that copy is newer', () => {
    const db = migratedTo(5)
    insertSong(db, {
      id: 'older-no-file',
      serverSongId: 7,
      sourceUrl: SAME,
      fileUri: null,
      addedAt: '2026-07-01T00:00:00Z',
    })
    insertSong(db, {
      id: 'newer-with-file',
      serverSongId: null,
      sourceUrl: SAME,
      fileUri: 'file:///newer.opus',
      addedAt: '2026-08-01T00:00:00Z',
    })
    insertPlaylist(db, 'p1', null)
    insertItem(db, 'i1', 'p1', 'older-no-file', 0)

    db.exec(MIGRATIONS[5])

    // The repoint and the delete order candidates the same way, or the playlist
    // is left pointing at a row that has just been deleted — a track that plays
    // from nowhere. Pinned separately because the two statements are far apart
    // in the SQL and only agree by intent.
    expect(db.prepare('SELECT song_id FROM playlist_items').all()).toEqual([
      { song_id: 'newer-with-file' },
    ])
    expect(db.prepare('SELECT id FROM songs').all()).toEqual([{ id: 'newer-with-file' }])
  })

  it('does not throw when a playlist holds both copies', () => {
    const db = migratedTo(5)
    insertSong(db, {
      id: 'keeper',
      serverSongId: 7,
      sourceUrl: SAME,
      fileUri: 'file:///a.opus',
      addedAt: '2026-07-01T00:00:00Z',
    })
    insertSong(db, { id: 'loser', serverSongId: null, sourceUrl: SAME, fileUri: null })
    insertPlaylist(db, 'p1', null)
    insertItem(db, 'i1', 'p1', 'keeper', 0)
    insertItem(db, 'i2', 'p1', 'loser', 1)

    // `playlist_items` has a UNIQUE index on (playlist_id, song_id) — a local
    // playlist may not hold the same song twice, deliberately, since v3. So
    // repointing the second row onto the first violates it, the transaction
    // rolls back, and the device cannot open its library. This is the case that
    // has to be cleared before the repoint, not after.
    expect(() => db.exec(MIGRATIONS[5])).not.toThrow()

    const items = db.prepare('SELECT song_id FROM playlist_items').all()
    expect(items).toEqual([{ song_id: 'keeper' }])
  })

  it('leaves different songs completely alone', () => {
    const db = migratedTo(5)
    insertSong(db, { id: 'a', serverSongId: null, sourceUrl: `${SAME}1`, fileUri: null })
    insertSong(db, { id: 'b', serverSongId: null, sourceUrl: `${SAME}2`, fileUri: null })

    db.exec(MIGRATIONS[5])

    expect(db.prepare('SELECT COUNT(*) AS n FROM songs').get()).toEqual({ n: 2 })
  })

  it('refuses a duplicate source from then on', () => {
    const db = migratedTo(6)
    insertSong(db, { id: 'a', serverSongId: null, sourceUrl: SAME, fileUri: null })

    // The point of the index: the old check-then-insert was not race-protected,
    // so two runs could both decide the row was missing.
    expect(() =>
      insertSong(db, { id: 'b', serverSongId: 9, sourceUrl: SAME, fileUri: null }),
    ).toThrow()
  })

  it('gives an import its own id column, so it cannot collide with a playlist', () => {
    const db = migratedTo(6)
    // Import #7 and server playlist #7 both exist. Before v6 these were one
    // UNIQUE column and the second insert failed — or worse, found the first.
    insertPlaylist(db, 'from-handover', 7)
    db.prepare(
      `INSERT INTO playlists (id, name, kind, created_at, updated_at, server_import_id)
       VALUES (?, ?, 'user', ?, ?, ?)`,
    ).run('from-import', 'Imported', '2026-08-01T00:00:00Z', '2026-08-01T00:00:00Z', 7)

    // Filtered to user playlists: v3 seeds a 'favourites' row, and counting it
    // here would make this test about the wrong thing.
    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 2,
    })
  })
})

describe('the v7 migration — a playlist remembers its Google playlist (#106)', () => {
  const insertServer = (db: DatabaseSync, id: string, serverPlaylistId: number | null) =>
    db
      .prepare(
        `INSERT INTO playlists (id, name, kind, created_at, updated_at, server_playlist_id)
         VALUES (?, ?, 'user', ?, ?, ?)`,
      )
      .run(id, `Playlist ${id}`, '2026-08-13T00:00:00Z', '2026-08-13T00:00:00Z', serverPlaylistId)

  const insertGoogle = (db: DatabaseSync, id: string, googleId: string | null) =>
    db
      .prepare(
        `INSERT INTO playlists (id, name, kind, created_at, updated_at, google_playlist_id)
         VALUES (?, ?, 'user', ?, ?, ?)`,
      )
      .run(id, `Playlist ${id}`, '2026-08-13T00:00:00Z', '2026-08-13T00:00:00Z', googleId)

  it('keeps every playlist that was already here', () => {
    const db = migratedTo(6)
    insertServer(db, 'mine', null)

    db.exec(MIGRATIONS[6])

    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 1,
    })
  })

  it('refuses a second playlist for the same Google playlist', () => {
    // The whole point of the column: re-importing must fill in the playlist
    // already here rather than building a second copy beside it.
    const db = migratedTo(7)
    insertGoogle(db, 'first', 'PLabc')

    expect(() => insertGoogle(db, 'second', 'PLabc')).toThrow()
  })

  it('lets every playlist that has nothing to do with Google keep a null', () => {
    // NULLs are distinct in a SQLite UNIQUE index. If they were not, the second
    // ordinary playlist a user made would be refused — which is the failure
    // mode worth a test rather than an assumption.
    const db = migratedTo(7)
    insertGoogle(db, 'one', null)
    insertGoogle(db, 'two', null)

    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 2,
    })
  })

  it('does not collide with the two server id columns', () => {
    const db = migratedTo(7)
    // A string id from YouTube and an integer id from our own server, which is
    // exactly the pair v6 had to rebuild a table to separate.
    insertServer(db, 'from-handover', 7)
    insertGoogle(db, 'from-google', 'PL7')

    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 2,
    })
  })
})

describe('the v8 migration — a playlist remembers its Bilibili folder (#492)', () => {
  const insertBilibili = (db: DatabaseSync, id: string, favId: string | null) =>
    db
      .prepare(
        `INSERT INTO playlists (id, name, kind, created_at, updated_at, bilibili_fav_id)
         VALUES (?, ?, 'user', ?, ?, ?)`,
      )
      .run(id, `Playlist ${id}`, '2026-08-15T00:00:00Z', '2026-08-15T00:00:00Z', favId)

  it('keeps every playlist that was already here', () => {
    const db = migratedTo(7)
    db.prepare(
      `INSERT INTO playlists (id, name, kind, created_at, updated_at, google_playlist_id)
       VALUES (?, ?, 'user', ?, ?, ?)`,
    ).run('mine', 'Mine', '2026-08-15T00:00:00Z', '2026-08-15T00:00:00Z', 'PLabc')

    db.exec(MIGRATIONS[7])

    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 1,
    })
  })

  it('refuses a second playlist for the same folder', () => {
    // The whole point of the column: re-importing a living folder must fill in
    // the playlist already here rather than build a second copy beside it.
    const db = migratedTo(8)
    insertBilibili(db, 'first', '486002245')

    expect(() => insertBilibili(db, 'second', '486002245')).toThrow()
  })

  it('lets every playlist that has nothing to do with Bilibili keep a null', () => {
    // NULLs are distinct in a SQLite UNIQUE index. If they were not, the second
    // ordinary playlist a user made would be refused — which is the failure
    // mode worth a test rather than an assumption.
    const db = migratedTo(8)
    insertBilibili(db, 'one', null)
    insertBilibili(db, 'two', null)

    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 2,
    })
  })

  it('does not collide with the Google column, whose ids are also strings', () => {
    /*
     * The reason these are two columns rather than one `source_id` plus a
     * platform: the UNIQUE index would then have to be on the *pair*, and NULLs
     * are distinct in a SQLite UNIQUE index — so every hand-made playlist would
     * carry a NULL platform and the index would constrain nothing at all.
     *
     * A Bilibili `media_id` is bare digits and a YouTube playlist id starts
     * `PL`, so a shared column would not collide *today*. That is luck, and
     * this asserts the structure instead.
     */
    const db = migratedTo(8)
    db.prepare(
      `INSERT INTO playlists (id, name, kind, created_at, updated_at, google_playlist_id)
       VALUES (?, ?, 'user', ?, ?, ?)`,
    ).run('from-google', 'From YouTube', '2026-08-15T00:00:00Z', '2026-08-15T00:00:00Z', '12345')
    insertBilibili(db, 'from-bilibili', '12345')

    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 2,
    })
  })
})

describe('the v9 migration — a playlist remembers its multi-part video (#575)', () => {
  const insertVideo = (db: DatabaseSync, id: string, bvid: string | null) =>
    db
      .prepare(
        `INSERT INTO playlists (id, name, kind, created_at, updated_at, bilibili_video_id)
         VALUES (?, ?, 'user', ?, ?, ?)`,
      )
      .run(id, `Playlist ${id}`, '2026-08-17T00:00:00Z', '2026-08-17T00:00:00Z', bvid)

  it('keeps every playlist that was already here', () => {
    const db = migratedTo(8)
    db.prepare(
      `INSERT INTO playlists (id, name, kind, created_at, updated_at, bilibili_fav_id)
       VALUES (?, ?, 'user', ?, ?, ?)`,
    ).run('mine', 'Mine', '2026-08-17T00:00:00Z', '2026-08-17T00:00:00Z', '486002245')

    db.exec(MIGRATIONS[8])

    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 1,
    })
  })

  it('refuses a second playlist for the same video', () => {
    // The point of the column: importing four parts today and the other
    // twenty-nine next week must fill in the playlist already here.
    const db = migratedTo(9)
    insertVideo(db, 'first', 'BV1r84y1e77t')

    expect(() => insertVideo(db, 'second', 'BV1r84y1e77t')).toThrow()
  })

  it('lets every playlist that has nothing to do with a video keep a null', () => {
    // NULLs are distinct in a SQLite UNIQUE index — if they were not, the
    // second ordinary playlist a user made would be refused. The failure mode
    // worth a test rather than an assumption, as v7 and v8 both found.
    const db = migratedTo(9)
    insertVideo(db, 'one', null)
    insertVideo(db, 'two', null)

    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 2,
    })
  })

  it('is its own column, so a folder and a video cannot collide', () => {
    /*
     * ⚠️ A favourites `media_id` is bare digits and a `bvid` starts `BV`, so a
     * shared column would not collide *today*. That is luck. This asserts the
     * structure instead — the third column v8's comment predicted would be
     * worth paying for.
     */
    const db = migratedTo(9)
    db.prepare(
      `INSERT INTO playlists (id, name, kind, created_at, updated_at, bilibili_fav_id)
       VALUES (?, ?, 'user', ?, ?, ?)`,
    ).run('from-folder', 'A folder', '2026-08-17T00:00:00Z', '2026-08-17T00:00:00Z', 'BV1r84y1e77t')
    insertVideo(db, 'from-video', 'BV1r84y1e77t')

    expect(db.prepare("SELECT COUNT(*) AS n FROM playlists WHERE kind = 'user'").get()).toEqual({
      n: 2,
    })
  })
})
