/**
 * The mobile half of the cross-language matching guard (#609).
 *
 * `shared/matching-golden.json` is generated by
 * `backend/scripts/dump_matching_golden.py` from `app/matching.py`. This suite
 * asserts the TypeScript port reproduces it exactly;
 * `backend/tests/test_matching_golden.py` asserts Python still does too.
 *
 * ⚠️ **If this fails, do not regenerate the fixture to make it pass.** The
 * fixture is the specification. Regenerating it hides the divergence, which is
 * the entire failure mode this guard exists to prevent — #353 split matching
 * so it *could not* drift, and #608 traded that for this.
 *
 * The three layers are asserted separately so a failure names which one broke
 * rather than reporting one opaque number.
 */

import golden from '@mio/shared/matching-golden.json'

import {
  AUTO_THRESHOLD,
  CANDIDATE_LIMIT,
  REVIEW_THRESHOLD,
  buildSearchQuery,
  classify,
  normalize,
  scoreCandidates,
  tokenSetRatio,
  type ScorableResult,
} from '../src/library/matching'

describe('matching golden fixture', () => {
  it('has actually loaded a corpus', () => {
    // A control. Every assertion below is inside a loop, so an empty fixture
    // would make this whole suite pass while proving nothing (#523).
    expect(golden.cases.length).toBeGreaterThan(5)
    expect(golden.normalize.length).toBeGreaterThan(5)
    expect(golden.token_set_ratio.length).toBeGreaterThan(5)
  })

  it('agrees on the thresholds', () => {
    expect(AUTO_THRESHOLD).toBe(golden.thresholds.auto)
    expect(REVIEW_THRESHOLD).toBe(golden.thresholds.review)
    expect(CANDIDATE_LIMIT).toBe(golden.thresholds.candidate_limit)
  })

  describe('normalize()', () => {
    for (const entry of golden.normalize) {
      it(`folds ${JSON.stringify(entry.input)}`, () => {
        expect(normalize(entry.input)).toBe(entry.output)
      })
    }
  })

  describe('tokenSetRatio()', () => {
    for (const entry of golden.token_set_ratio) {
      it(`scores ${JSON.stringify(entry.a)} against ${JSON.stringify(entry.b)}`, () => {
        // The fixture stores `_similarity`, which is the ratio over 100.
        expect(tokenSetRatio(entry.a, entry.b) / 100).toBeCloseTo(entry.ratio, 12)
      })
    }
  })

  describe('scoreCandidates()', () => {
    for (const testCase of golden.cases) {
      describe(testCase.name, () => {
        const scored = scoreCandidates(
          testCase.title,
          testCase.artist,
          testCase.duration_s,
          testCase.results as ScorableResult[],
        )
        const expected = testCase.expected.scored

        it('returns the candidates in the same order', () => {
          expect(scored.map((candidate) => candidate.url)).toEqual(
            expected.map((candidate) => candidate.url),
          )
        })

        it('gives each candidate the same score', () => {
          expect(scored).toHaveLength(expected.length)
          scored.forEach((candidate, index) => {
            expect(candidate.score).toBeCloseTo(expected[index].score, 12)
            expect(candidate.source).toBe(expected[index].source)
          })
        })

        it('builds the same search query', () => {
          // ⚠️ #618: the device carried its own builder that did not split the
          // artist on a comma, so multi-artist tracks were searched with a
          // noisier string than the scorer expects. Asserted here so the two
          // cannot drift again.
          expect(buildSearchQuery(testCase.title, testCase.artist)).toBe(testCase.expected.query)
        })

        it('classifies the track the same way', () => {
          const best = scored.length > 0 ? scored[0].score : null
          expect(classify(best)).toBe(testCase.expected.status)
        })
      })
    }
  })
})
