"""add owner_key_id to library tables

Revision ID: 1220936506e0
Revises: 56a066fc4e19
Create Date: 2026-07-25 15:35:51.438066

Per-access-key library isolation (P12). Every library row records which access
key created it; a caller sees only their own rows.

Nullable, and NOT back-filled on purpose: existing rows predate any key and
belong to the local, unowned library. `current_owner_key_id` maps "no key
presented" to exactly those rows, so a single-user local install keeps working
untouched.

Hand-edited away from the autogenerated draft in two places:

1. Alembic proposed re-typing `playlists.kind` from VARCHAR to its Enum. SQLite
   cannot execute that statement at all, and the Docker image runs
   `alembic upgrade head` on boot, so it would stop the app starting. This is
   the same spurious diff G4 hit; `tests/test_loudness_migration.py` exists
   because of it.
2. No database-level foreign key is created. SQLite has no
   `ALTER TABLE ... ADD CONSTRAINT`, and alembic raises `NotImplementedError`
   for it — including for a `ForeignKey` declared inline on `add_column`. The
   alternative is batch mode, which rebuilds each table by copy-and-move.
   That is a lot of risk for a constraint SQLite would not enforce anyway
   unless `PRAGMA foreign_keys` is on, which is the same reasoning already
   applied to `Song.playlist_items` cascades in `app/models.py`. The ORM still
   declares the relationship, so joins and typing are unaffected.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1220936506e0"
down_revision: Union[str, Sequence[str], None] = "56a066fc4e19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLES = ("songs", "playlists", "import_jobs", "playlist_imports")


def upgrade() -> None:
    """Upgrade schema."""
    for table in _TABLES:
        op.add_column(table, sa.Column("owner_key_id", sa.Integer(), nullable=True))
        op.create_index(
            op.f(f"ix_{table}_owner_key_id"), table, ["owner_key_id"], unique=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_TABLES):
        op.drop_index(op.f(f"ix_{table}_owner_key_id"), table_name=table)
        op.drop_column(table, "owner_key_id")
