"""add installs, and move library ownership onto them

Revision ID: 2f4c81ab90de
Revises: 1220936506e0
Create Date: 2026-07-30 01:40:00.000000

Ownership moves from the access key to an *install* (#170).

P12 answered two different questions with one column. A keyless caller's rows
were owned by nobody, so every keyless caller shared one library; and presenting
a key later re-scoped every read, hiding everything imported before it. Splitting
them means a key gates search and import, and nothing else.

`owner_install_id` is nullable and **not** back-filled. Rows carrying the old
`owner_key_id`, and rows predating that too, end up owned by nobody — and unlike
under P12, "owned by nobody" is now seen by nobody, because every client sends an
install id. That is deliberate: the alternative is guessing which install should
adopt an existing library, and guessing wrong hands one person's music to
another. My call, 2026-07-30 — the pre-existing rows are disposable.

`owner_key_id` is dropped rather than kept alongside. Two owner columns, one of
them dead, is the kind of thing that gets read by accident a year later.

Hand-written rather than autogenerated, for the reasons the P12 migration
(1220936506e0) already records and which have not changed:

1. **No database-level foreign key.** SQLite has no
   `ALTER TABLE ... ADD CONSTRAINT`, and alembic raises `NotImplementedError`
   even for a `ForeignKey` declared inline on `add_column`. Batch mode would
   rebuild every table by copy-and-move — a lot of risk for a constraint SQLite
   would not enforce anyway without `PRAGMA foreign_keys`. The ORM still declares
   the relationship, so typing and joins are unaffected.
2. **Nothing is done to `playlists.kind`.** Autogenerate keeps proposing a
   VARCHAR-to-Enum retype that SQLite cannot execute at all. The image runs
   `alembic upgrade head` on boot, so accepting that draft would stop the app
   starting. `tests/test_install_migration.py` runs the real migrations against a
   throwaway database so this cannot come back.

Dropping a column *does* need batch mode on SQLite, which is why the downgrade
and the drop use it explicitly.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f4c81ab90de"
down_revision: Union[str, Sequence[str], None] = "1220936506e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLES = ("songs", "playlists", "import_jobs", "playlist_imports")


def upgrade() -> None:
    op.create_table(
        "installs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_installs_token_hash"), "installs", ["token_hash"], unique=True)

    for table in _TABLES:
        op.add_column(table, sa.Column("owner_install_id", sa.Integer(), nullable=True))
        op.create_index(
            op.f(f"ix_{table}_owner_install_id"), table, ["owner_install_id"], unique=False
        )
        # Batch mode: SQLite cannot DROP COLUMN in place, so alembic rebuilds the
        # table. Safe here because the column is being removed rather than
        # re-typed, and nothing references it.
        with op.batch_alter_table(table) as batch:
            batch.drop_index(op.f(f"ix_{table}_owner_key_id"))
            batch.drop_column("owner_key_id")


def downgrade() -> None:
    for table in _TABLES:
        op.add_column(table, sa.Column("owner_key_id", sa.Integer(), nullable=True))
        op.create_index(op.f(f"ix_{table}_owner_key_id"), table, ["owner_key_id"], unique=False)
        with op.batch_alter_table(table) as batch:
            batch.drop_index(op.f(f"ix_{table}_owner_install_id"))
            batch.drop_column("owner_install_id")

    op.drop_index(op.f("ix_installs_token_hash"), table_name="installs")
    op.drop_table("installs")
