"""add song.audio_released_at

Revision ID: 994789b23f00
Revises: a0602ce67dcb
Create Date: 2026-08-06

#221 / ADR-017: when a device confirmed it holds the audio and the server
deleted its own copy. Null means the server still has the file.

Nullable with no default, and that is the whole migration — every existing row
is a song the server still holds, which is exactly what null means. The
autogenerated draft carried seven other operations and none of them was a real
change; see a0602ce67dcb for the same story. An autogenerated migration is a
draft, not a diff.
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "994789b23f00"
down_revision: Union[str, Sequence[str], None] = "a0602ce67dcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("songs", sa.Column("audio_released_at", sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("songs", "audio_released_at")
