"""add playlist_import.client_matches

Revision ID: a0602ce67dcb
Revises: f2b81d4a6c07
Create Date: 2026-08-06 13:43:52.807298

#353: whether the *client* supplies the YouTube candidates for each track.
False keeps the historical behaviour, where the matching phase searches
YouTube itself.

The autogenerated draft carried six other operations and none of them was a
real change — SQLite reflection reports unnamed foreign keys and the
`native_enum=False` column as differences on every run. Applying them would
rebuild four tables to achieve nothing. This is the one line that was actually
a diff, which is why this project treats an autogenerated migration is a draft.

`server_default` matters as much as the type: the column is NOT NULL and the
table has rows, so the database needs an answer for the rows already there —
the ORM default only applies to rows the ORM inserts. Same reasoning as
`access_key.is_admin` in f2b81d4a6c07.
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0602ce67dcb"
down_revision: Union[str, Sequence[str], None] = "f2b81d4a6c07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "playlist_imports",
        sa.Column("client_matches", sa.Boolean(), server_default=sa.text("0"), nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("playlist_imports", "client_matches")
