"""create google_accounts

Revision ID: bf6f22dfc30a
Revises: 994789b23f00
Create Date: 2026-08-12 20:29:02.238015

Hand-trimmed. Autogenerate also proposed a `playlists.kind` type change, four
`owner_install_id` foreign keys and a unique-constraint swap on
`client_errors.client_key` — none of which this change makes. They are standing
drift between the models and the migration history, mostly from SQLite not
enforcing the constraints the ORM declares, and carrying them here would mean a
migration named for one thing quietly performing five others. An autogenerated
migration is a draft, not a diff.

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf6f22dfc30a"
down_revision: Union[str, Sequence[str], None] = "994789b23f00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "google_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(length=100), nullable=False),
        sa.Column("channel_title", sa.String(length=300), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scopes", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # Unique: one row per YouTube channel, so reconnecting — which happens every
    # seven days while the consent screen is in Testing — updates the account
    # rather than adding another one every week.
    op.create_index(
        op.f("ix_google_accounts_channel_id"), "google_accounts", ["channel_id"], unique=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_google_accounts_channel_id"), table_name="google_accounts")
    op.drop_table("google_accounts")
