"""add client_errors

Revision ID: d1f145b13692
Revises: 2f4c81ab90de
Create Date: 2026-07-30 19:24:45.165921

Hand-edited down to the one table this change adds. Autogenerate also proposed
re-typing `playlists.kind` from VARCHAR to an Enum and adding four foreign keys
on `owner_install_id` — none of which this change asks for, and the first of
which **SQLite cannot execute at all**. The image runs `alembic upgrade head` on
boot, so shipping that would have stopped the app starting.

Not a surprise: the identical proposal appearing during G4,
and `tests/test_loudness_migration.py` exists because of it. Autogenerated
migrations are a draft, not a diff.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1f145b13692"
down_revision: Union[str, Sequence[str], None] = "2f4c81ab90de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "client_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("stack", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("app_version", sa.String(length=64), nullable=True),
        sa.Column("os_version", sa.String(length=64), nullable=True),
        sa.Column("device", sa.String(length=200), nullable=True),
        # Deliberately not a foreign key to `installs.id`: a crash report has to
        # outlive the install that produced it. Losing crash history to a
        # cascade is a poor trade for referential tidiness.
        sa.Column("owner_install_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("client_errors")
