"""create playlist import and track match

Revision ID: fe75f257b4df
Revises: 76e1c7bf22e3
Create Date: 2026-07-23 13:29:36.747413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe75f257b4df'
down_revision: Union[str, Sequence[str], None] = '76e1c7bf22e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('external_playlist_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'FETCHING', 'MATCHING', 'REVIEW', 'IMPORTING', 'DONE', 'FAILED', name='playlistimportstatus', native_enum=False), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('import_total', sa.Integer(), nullable=True),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['spotify_accounts.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_import_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=False),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('chosen_url', sa.String(length=2000), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'AUTO_MATCHED', 'NEEDS_REVIEW', 'NO_MATCH', 'ACCEPTED', 'REJECTED', 'IMPORTED', 'FAILED', name='trackmatchstatus', native_enum=False), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.ForeignKeyConstraint(['playlist_import_id'], ['playlist_imports.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_matches_playlist_import_id'), 'track_matches', ['playlist_import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_matches_playlist_import_id'), table_name='track_matches')
    op.drop_table('track_matches')
    op.drop_table('playlist_imports')
    # ### end Alembic commands ###
